### ISSUE TITLE
Introduce `dotnet ws build` to streamline compilation

### ISSUE THREAD

**Issue by mrtank** [dotnet-websharper/dotnet-ws#6]
When compiling WebSharper projects, the F# and WebSharper `msbuild` targets files are executed first (resolving project/package references, compiler flags, etc.), and the WebSharper compiler, `wsfsc.exe`, is called with the results. What we find is that the `msbuild` computation preceeding the main compiler call can take a significant amount of time (on the order of a couple seconds), and for a typical edit-compile-run scenario executing this computation over and over is pointless. Given that the Booster can easily be made to cache more build information, it makes sense to investigate ways to make certain projects bypass this msbuild preamble, thus saving the time otherwise spent there. This ticket represents the work behind such a possible `dotnet ws build` command.

Some notes/caveats:

 * WebSharper projects that rely on custom msbuild logic to copy compilation artifacts (both source and target) **will likely fail to run/refresh properly**, given that those build steps are omitted. That said, this proposal would make compilation significantly faster, among others, for client-side changes in [Bundle/BundleOnly/HTML/Site](https://developers.websharper.com/docs/v4.x/fs/templates) projects (more info about [project variables](https://developers.websharper.com/docs/v4.x/fs/project-variables)). Here, the guideline would have you call `dotnet ws build` for a faster re-compilation of `js`+`html`+`css` output instead of `dotnet build`.

 * Using `dotnet ws build` requires that **none of the project dependencies changed** (the list of [`-r` arguments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/inputs#references)) since the last compilation. If such dependency changes are present, `dotnet build` should be called instead.

Further technical notes:

 * `dotnet ws build` would first identify whether a Booster with the desired runtime (targeting a specific version of WebSharper) is running and send a compilation request to it (`[|"compile:myProject.fsproj"|]`, or something similar.) If that Booster has cached the project at hand, it proceeds to recompile it, giving a possible warning if we suspect that a full msbuild circle might be needed to get everything in place (for now, we can just flag this based on the output project type.)

 * If the project is not in the Booster's cache or the desired Booster is not yet running, we should fall back to executing `dotnet build` to get everything initialized properly.

 * The Booster already caches the metadata for a build [here](https://github.com/dotnet-websharper/core/blob/3a455dcc9153c1db59d245b6a50852e281fc658a/src/compiler/WebSharper.FSharp.Service/Program.fs#L50-L69). We can use the same invalidation logic and even the same `memCache` instance to skip the first step when plausible. 

 * Implementation would keep a mutable `Dictionary` with the project file paths as keys, and arguments as values. When a cache is invalidated in `memCache` we can remove every project containing that assembly, and let next compilation with `msbuild` re-add the entry.

**Comment by granicz** [comment]
This command should also have a `--project`/`-p` flag to supply the project file. Note, however, that we should also be able to issue `dotnet ws build`, without specifying a project file, from anywhere within a given project folder. This means that we need to find the corresponding project file starting from the CWD, walking up until we run out of folders or find a single, unique project file. The direction is always up, never sinking down into sibling folders.

This also means that we have to be careful about what folder to trigger `dotnet build` FROM, when falling back to it. I think that folder should just be the folder that contains the project file.

**Comment by granicz** [comment]
One implementation strategy for the "identify whether a Booster with the desired runtime is running" clause above would be to read the WebSharper version from the project file (or better yet, from `obj/project.nuget.cache`) and using that to find the service instance.
